import { GraphNodeHandler } from "../stateGraph/types.js";
import { writeRunArtifact } from "./helpers.js";
import { NodeExecutionDeps } from "./types.js";

export function createWritePaperNode(deps: NodeExecutionDeps): GraphNodeHandler {
  return {
    id: "write_paper",
    async execute({ run, graph }) {
      const tex = [
        "\\documentclass{article}",
        "\\usepackage{graphicx}",
        "\\title{AutoResearch Draft}",
        "\\begin{document}",
        "\\maketitle",
        "\\section{Introduction}",
        `Topic: ${latexEscape(run.topic)}.`,
        "\\section{Method}",
        "See experiment plan and implementation artifacts.",
        "\\section{Results}",
        "Metrics are linked with evidence IDs in metadata.",
        "\\section{Conclusion}",
        "This draft was generated by AutoResearch state graph runtime.",
        "\\bibliographystyle{plain}",
        "\\bibliography{references}",
        "\\end{document}"
      ].join("\n");

      const references = [
        "@article{autoref1,",
        "  title={AutoResearch generated reference},",
        "  author={AutoResearch},",
        "  year={2026}",
        "}"
      ].join("\n");

      const evidenceMap = JSON.stringify(
        {
          claims: [
            { claim_id: "c1", evidence_ids: ["ev_1"] },
            { claim_id: "c2", evidence_ids: ["ev_2"] }
          ]
        },
        null,
        2
      );

      await writeRunArtifact(run, "paper/main.tex", tex);
      await writeRunArtifact(run, "paper/references.bib", references);
      await writeRunArtifact(run, "paper/evidence_links.json", evidenceMap);

      deps.eventStream.emit({
        type: "NODE_COMPLETED",
        runId: run.id,
        node: "write_paper",
        payload: { artifacts: ["paper/main.tex", "paper/references.bib"] }
      });

      return {
        status: "success",
        summary: "Paper draft generated in LaTeX.",
        needsApproval: true,
        toolCallsUsed: 1
      };
    }
  };
}

function latexEscape(text: string): string {
  return text.replace(/[&_#%$]/g, " ").trim();
}
